# This is a basic workflow to help you get started with Actions

name: New Release!

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Move_old_releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check old release existence
        id: check_files
        uses: andstor/file-existence-action@v1.1.0
        with:
          files: "releases"

      - name: Add old release into archive
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          export notfound=true
          while $notfound;
          do
            export testdir=0
            if [ -d "$testdir" ];
            then
              echo $testdir exits
              $testdir++
            else
              echo $testdir doesnt exists!
              unset notfound
            fi
          done
          
          mv $GITHUB_WORKSPACE/release/ $GITHUB_WORKSPACE/archive/$testdir/
      
      - name: Create new release folder
        run: mkdir $GITHUB_WORKSPACE/release/
  
  Zip_New_Files:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      
      - name: 1.11 - 1.12.2
        run: |
          cp lastest $GITHUB_WORKSPACES/tmp
          
      - name: 1.11 - 1.12.2 2
      - uses: 1arp/create-a-file-action@0.2
        with:
          path: 'tmp/lastest'
          file: 'pack.mcmeta'
          content: |
            {
                "pack": {
                    "pack_format": 3,
                    "description": "\u00a76demirium totem\n\u00a7etwitch.tv/demirium_"
                }
            }
            
      - name: 1.11 - 1.12.2 3
      - run: cat version.txt; VERSION=$(cat -); echo $VERSION
      
      - name: 1.11 - 1.12.2 4
      - uses: 1arp/create-a-file-action@0.2
        with:
          file: 'version.txt'
          content: $VERSION++
      
      - name: 1.11 - 1.12.2 5
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release/$VERSION/3/demirium_totem.zip lastest
      
      
          

        
# This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       #- name: Run a one-line script
#       #  run: echo Hello, world!

#       # Runs a set of commands using the runners shell
# #       - name: Run a multi-line script
# #         run: |
# #           echo Add other actions to build,
# #           echo test, and deploy your project.
